-- Registros fictícios de uso, apenas para demonstração do Dashboard do
-- Inventário de Sistemas de IA. Nomes, e-mails (@monstros.com.br) e
-- chamados são inventados. Rode depois do catálogo (não é idempotente —
-- rodar duas vezes duplica as linhas).

INSERT INTO sistemas_ia (
  sistema, tipo, descricao, area, area_usuario, usuarios, emails,
  dados_tratados, parecer_aprovado, parecer_numero_chamado
) VALUES
  ('Claude', 'Texto/Chat', 'Uso de Claude pela área de Tecnologia da Informação, aplicado a tarefas de texto/chat.', 'Tecnologia da Informação', 'Jurídico', 'Marina Kowalski', 'marina.kowalski@monstros.com.br', 'Pessoais', true, 'CYBER-1000'),
  ('ChatGPT', 'Texto/Chat', 'Uso de ChatGPT pela área de Recursos Humanos, aplicado a tarefas de texto/chat.', 'Recursos Humanos', 'Comercial / Vendas', 'Renato Bousquet; Patrícia Neumann', 'renato.bousquet@monstros.com.br; patricia.neumann@monstros.com.br', 'Negócio, Pessoais', false, NULL),
  ('Google Gemini', 'Texto/Chat', 'Uso de Google Gemini pela área de Financeiro, aplicado a tarefas de texto/chat.', 'Financeiro', 'Marketing', 'Alana Ferreira; Rafael Trindade; Isabela Cordovil', 'alana.ferreira@monstros.com.br; rafael.trindade@monstros.com.br; isabela.cordovil@monstros.com.br', NULL, false, NULL),
  ('Microsoft Copilot', 'Texto/Chat', 'Uso de Microsoft Copilot pela área de Jurídico, aplicado a tarefas de texto/chat.', 'Jurídico', 'Operações', 'Thiago Almendra', 'thiago.almendra@monstros.com.br', 'Pessoais', NULL, NULL),
  ('GitHub Copilot', 'Desenvolvimento', 'Uso de GitHub Copilot pela área de Comercial / Vendas, aplicado a tarefas de desenvolvimento.', 'Comercial / Vendas', 'Atendimento ao Cliente', 'Camila Duprat; Diego Salviano', 'camila.duprat@monstros.com.br; diego.salviano@monstros.com.br', 'Negócio, Pessoais', false, NULL),
  ('Mistral AI', 'Texto/Chat', 'Uso de Mistral AI pela área de Marketing, aplicado a tarefas de texto/chat.', 'Marketing', 'Diretoria', 'Fábio Restier; Vanessa Mourão; André Cavalcanti', 'fabio.restier@monstros.com.br; vanessa.mourao@monstros.com.br; andre.cavalcanti@monstros.com.br', NULL, false, NULL),
  ('DeepSeek', 'Texto/Chat', 'Uso de DeepSeek pela área de Operações, aplicado a tarefas de texto/chat.', 'Operações', 'Tecnologia da Informação', 'Juliana Vasconcelos', 'juliana.vasconcelos@monstros.com.br', 'Pessoais', true, 'CYBER-1006'),
  ('Perplexity', 'Texto/Chat', 'Uso de Perplexity pela área de Atendimento ao Cliente, aplicado a tarefas de texto/chat.', 'Atendimento ao Cliente', 'Recursos Humanos', 'Bruno Katsuo; Carolina Brandão', 'bruno.katsuo@monstros.com.br; carolina.brandao@monstros.com.br', 'Negócio, Pessoais', NULL, NULL),
  ('Meta AI', 'Texto/Chat', 'Uso de Meta AI pela área de Diretoria, aplicado a tarefas de texto/chat.', 'Diretoria', 'Financeiro', 'Patrícia Neumann; Gustavo Lemgruber; Alana Ferreira', 'patricia.neumann@monstros.com.br; gustavo.lemgruber@monstros.com.br; alana.ferreira@monstros.com.br', NULL, false, NULL),
  ('Llama', 'Desenvolvimento', 'Uso de Llama pela área de Tecnologia da Informação, aplicado a tarefas de desenvolvimento.', 'Tecnologia da Informação', 'Jurídico', 'Rafael Trindade', 'rafael.trindade@monstros.com.br', 'Pessoais', true, 'CYBER-1009'),
  ('Midjourney', 'Imagem', 'Uso de Midjourney pela área de Recursos Humanos, aplicado a tarefas de imagem.', 'Recursos Humanos', 'Comercial / Vendas', 'Larissa Bittencourt; Leandro Fagundes', 'larissa.bittencourt@monstros.com.br; leandro.fagundes@monstros.com.br', 'Negócio, Pessoais', false, NULL),
  ('DALL-E', 'Imagem', 'Uso de DALL-E pela área de Financeiro, aplicado a tarefas de imagem.', 'Financeiro', 'Marketing', 'Diego Salviano; Priscila Vinhas; Fábio Restier', 'diego.salviano@monstros.com.br; priscila.vinhas@monstros.com.br; fabio.restier@monstros.com.br', NULL, NULL, NULL),
  ('Stable Diffusion', 'Imagem', 'Uso de Stable Diffusion pela área de Jurídico, aplicado a tarefas de imagem.', 'Jurídico', 'Operações', 'Vanessa Mourão', 'vanessa.mourao@monstros.com.br', 'Pessoais', true, 'CYBER-1012'),
  ('Adobe Firefly', 'Imagem', 'Uso de Adobe Firefly pela área de Comercial / Vendas, aplicado a tarefas de imagem.', 'Comercial / Vendas', 'Atendimento ao Cliente', 'Eduardo Pontes; Marina Kowalski', 'eduardo.pontes@monstros.com.br; marina.kowalski@monstros.com.br', 'Negócio, Pessoais', false, NULL),
  ('Leonardo AI', 'Imagem', 'Uso de Leonardo AI pela área de Marketing, aplicado a tarefas de imagem.', 'Marketing', 'Diretoria', 'Carolina Brandão; Renato Bousquet; Patrícia Neumann', 'carolina.brandao@monstros.com.br; renato.bousquet@monstros.com.br; patricia.neumann@monstros.com.br', NULL, false, NULL),
  ('Runway', 'Vídeo', 'Uso de Runway pela área de Operações, aplicado a tarefas de vídeo.', 'Operações', 'Tecnologia da Informação', 'Gustavo Lemgruber', 'gustavo.lemgruber@monstros.com.br', 'Pessoais', NULL, NULL),
  ('Synthesia', 'Vídeo', 'Uso de Synthesia pela área de Atendimento ao Cliente, aplicado a tarefas de vídeo.', 'Atendimento ao Cliente', 'Recursos Humanos', 'Isabela Cordovil; Thiago Almendra', 'isabela.cordovil@monstros.com.br; thiago.almendra@monstros.com.br', 'Negócio, Pessoais', false, NULL),
  ('HeyGen', 'Vídeo', 'Uso de HeyGen pela área de Diretoria, aplicado a tarefas de vídeo.', 'Diretoria', 'Financeiro', 'Leandro Fagundes; Camila Duprat; Diego Salviano', 'leandro.fagundes@monstros.com.br; camila.duprat@monstros.com.br; diego.salviano@monstros.com.br', NULL, false, NULL),
  ('Pika Labs', 'Vídeo', 'Uso de Pika Labs pela área de Tecnologia da Informação, aplicado a tarefas de vídeo.', 'Tecnologia da Informação', 'Jurídico', 'Priscila Vinhas', 'priscila.vinhas@monstros.com.br', 'Pessoais', true, 'CYBER-1018'),
  ('Sora', 'Vídeo', 'Uso de Sora pela área de Recursos Humanos, aplicado a tarefas de vídeo.', 'Recursos Humanos', 'Comercial / Vendas', 'André Cavalcanti; Juliana Vasconcelos', 'andre.cavalcanti@monstros.com.br; juliana.vasconcelos@monstros.com.br', 'Negócio, Pessoais', NULL, NULL),
  ('ElevenLabs', 'Outro', 'Uso de ElevenLabs pela área de Financeiro, aplicado a tarefas de outro.', 'Financeiro', 'Marketing', 'Marina Kowalski; Bruno Katsuo; Carolina Brandão', 'marina.kowalski@monstros.com.br; bruno.katsuo@monstros.com.br; carolina.brandao@monstros.com.br', NULL, false, NULL),
  ('Notion AI', 'Texto/Chat', 'Uso de Notion AI pela área de Jurídico, aplicado a tarefas de texto/chat.', 'Jurídico', 'Operações', 'Renato Bousquet', 'renato.bousquet@monstros.com.br', 'Pessoais', true, 'CYBER-1021'),
  ('Grammarly', 'Texto/Chat', 'Uso de Grammarly pela área de Comercial / Vendas, aplicado a tarefas de texto/chat.', 'Comercial / Vendas', 'Atendimento ao Cliente', 'Alana Ferreira; Rafael Trindade', 'alana.ferreira@monstros.com.br; rafael.trindade@monstros.com.br', 'Negócio, Pessoais', false, NULL),
  ('Jasper', 'Texto/Chat', 'Uso de Jasper pela área de Marketing, aplicado a tarefas de texto/chat.', 'Marketing', 'Diretoria', 'Thiago Almendra; Larissa Bittencourt; Leandro Fagundes', 'thiago.almendra@monstros.com.br; larissa.bittencourt@monstros.com.br; leandro.fagundes@monstros.com.br', NULL, NULL, NULL),
  ('Copy.ai', 'Texto/Chat', 'Uso de Copy.ai pela área de Operações, aplicado a tarefas de texto/chat.', 'Operações', 'Tecnologia da Informação', 'Camila Duprat', 'camila.duprat@monstros.com.br', 'Pessoais', true, 'CYBER-1024'),
  ('Codeium', 'Desenvolvimento', 'Uso de Codeium pela área de Atendimento ao Cliente, aplicado a tarefas de desenvolvimento.', 'Atendimento ao Cliente', 'Recursos Humanos', 'Fábio Restier; Vanessa Mourão', 'fabio.restier@monstros.com.br; vanessa.mourao@monstros.com.br', 'Negócio, Pessoais', false, NULL),
  ('Cursor', 'Desenvolvimento', 'Uso de Cursor pela área de Diretoria, aplicado a tarefas de desenvolvimento.', 'Diretoria', 'Financeiro', 'Juliana Vasconcelos; Eduardo Pontes; Marina Kowalski', 'juliana.vasconcelos@monstros.com.br; eduardo.pontes@monstros.com.br; marina.kowalski@monstros.com.br', NULL, false, NULL),
  ('Tabnine', 'Desenvolvimento', 'Uso de Tabnine pela área de Tecnologia da Informação, aplicado a tarefas de desenvolvimento.', 'Tecnologia da Informação', 'Jurídico', 'Bruno Katsuo', 'bruno.katsuo@monstros.com.br', 'Pessoais', NULL, NULL),
  ('Amazon Q Developer', 'Desenvolvimento', 'Uso de Amazon Q Developer pela área de Recursos Humanos, aplicado a tarefas de desenvolvimento.', 'Recursos Humanos', 'Comercial / Vendas', 'Patrícia Neumann; Gustavo Lemgruber', 'patricia.neumann@monstros.com.br; gustavo.lemgruber@monstros.com.br', 'Negócio, Pessoais', false, NULL),
  ('Replit AI', 'Desenvolvimento', 'Uso de Replit AI pela área de Financeiro, aplicado a tarefas de desenvolvimento.', 'Financeiro', 'Marketing', 'Rafael Trindade; Isabela Cordovil; Thiago Almendra', 'rafael.trindade@monstros.com.br; isabela.cordovil@monstros.com.br; thiago.almendra@monstros.com.br', NULL, false, NULL),
  ('v0', 'Desenvolvimento', 'Uso de v0 pela área de Jurídico, aplicado a tarefas de desenvolvimento.', 'Jurídico', 'Operações', 'Larissa Bittencourt', 'larissa.bittencourt@monstros.com.br', 'Pessoais', true, 'CYBER-1030'),
  ('Character.AI', 'Texto/Chat', 'Uso de Character.AI pela área de Comercial / Vendas, aplicado a tarefas de texto/chat.', 'Comercial / Vendas', 'Atendimento ao Cliente', 'Diego Salviano; Priscila Vinhas', 'diego.salviano@monstros.com.br; priscila.vinhas@monstros.com.br', 'Negócio, Pessoais', NULL, NULL),
  ('Otter.ai', 'Outro', 'Uso de Otter.ai pela área de Marketing, aplicado a tarefas de outro.', 'Marketing', 'Diretoria', 'Vanessa Mourão; André Cavalcanti; Juliana Vasconcelos', 'vanessa.mourao@monstros.com.br; andre.cavalcanti@monstros.com.br; juliana.vasconcelos@monstros.com.br', NULL, false, NULL),
  ('Fireflies.ai', 'Outro', 'Uso de Fireflies.ai pela área de Operações, aplicado a tarefas de outro.', 'Operações', 'Tecnologia da Informação', 'Eduardo Pontes', 'eduardo.pontes@monstros.com.br', 'Pessoais', true, 'CYBER-1033'),
  ('Wolfram Alpha', 'Cálculos', 'Uso de Wolfram Alpha pela área de Atendimento ao Cliente, aplicado a tarefas de cálculos.', 'Atendimento ao Cliente', 'Recursos Humanos', 'Carolina Brandão; Renato Bousquet', 'carolina.brandao@monstros.com.br; renato.bousquet@monstros.com.br', 'Negócio, Pessoais', false, NULL);
